const NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED';
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
const USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS';
const PASSWORD_IS_INCORRECT = 'PASSWORD_IS_INCORRECT';

module.exports = {
    NAME_OR_PASSWORD_IS_REQUIRED,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXISTS,
    PASSWORD_IS_INCORRECT
}